import { BrowserRouter as Router, Routes, Route } from "react-router-dom"
import Layout from "./components/Layout.tsx"
import Home from "./pages/Home.tsx"
import About from "./pages/About.tsx"
import Login from "./pages/auth/Login.tsx"
import Register from "./pages/auth/Register.tsx"
import BookAmbulance from "./pages/user/BookAmbulance.tsx"
import UserDashboard from "./pages/user/Dashboard.tsx"
import UserBookingHistory from "./pages/user/BookingHistory.tsx"
import UserTrackBooking from "./pages/user/TrackBooking.tsx"
import DriverDashboard from "./pages/driver/Dashboard.tsx"
import DriverBookings from "./pages/driver/Bookings.tsx"
import DriverProfile from "./pages/driver/Profile.tsx"
import DriverTrackBooking from "./pages/driver/TrackBooking.tsx"
import { AuthProvider } from "./contexts/AuthContext.tsx"
import { BookingProvider } from "./contexts/BookingContext.tsx"
